### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Toub** [littlepea/django-auction#11]
Hi @littlepea 

What is the license of this project?

**Comment by littlepea** [comment]
Hi @Toub !

Thanks for pointing out, I've just added [MIT](https://github.com/littlepea/django-auction/blob/develop/LICENSE) license

**Comment by Toub** [comment]
Thanks!

However, as your work is a fork of https://github.com/zpassenger/Django-Auction, itself create from Django Shop project, are you sure that the initial project is free of right or compatible with MIT license?

**Comment by littlepea** [comment]
How do you know it was created from Django Shop project?

I don't see any reference to django shop from Django-Auction...

**Comment by Toub** [comment]
In the readme: https://github.com/zpassenger/Django-Auction

> A Django auction system based on the Django Shop project.

**Comment by littlepea** [comment]
I can't see how it's based on https://github.com/awesto/django-shop I see no references, no similarities, nothing... Maybe is was inspired by it or something...

I guess only @zpassenger knows what he means by "based on the Django Shop project" :)
